/**
 * Created by tuxlin on 15/11/16.
 */

let postTasksData = () => {
	let data = {
		type: document.getElementById("optionSelect").value,
		data: {
			input: document.getElementById("inputText").value //output is generated by Bots
		}
	};

	let xhr = new XMLHttpRequest();
	xhr.open('POST', 'http://localhost:3000/api/Tasks', true);

	xhr.responseType = 'json';
	xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
	xhr.setRequestHeader('Token', '00530061006C00740079');

	xhr.send(JSON.stringify(data));
};

let refreshOnButtonPress = () => {
	$("#TasksTableToFill").html("");

	getData("Tasks", "id", (data) => {
		$("#TasksTableToFill").html("<tr>" + data.map((val, index) => {
			return "<td>" + val.id + "</td><td>" + val.type + "</td><td>" + val.data.input + "</td><td>" + val.data.output + "</td>";
		}).join("</tr><tr>") + "</tr>");
	});
};

$(document).ready(() => {
	refreshOnButtonPress();
});
